version: '3.4'

services:
  repeaters:
    image: repeaters
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      API_KEY: '643cd615b54b64e48a3fb8545de2d44c379d9798ba86e08c7b5559519dc050f3'
    ports:
      - 5001:5000
